/**
 *https://www.hackerrank.com/challenges/abbr/problem?h_r=internal-search
 * @param {string} letter
 * @returns {boolean}
 */
const isCapitalLetter = (letter) =>
  letter.charCodeAt(0) >= "A".charCodeAt(0) &&
  letter.charCodeAt(0) <= "Z".charCodeAt(0);

/**
 *
 * @param {string} a
 * @param {string} b
 * @returns {string}
 */
const abbreviationRec = (a, b) => {
  const memo = new Array(a.length)
    .fill(0)
    .map(() => new Array(b.length).fill(undefined));

  const solve = (i, j) => {
    if (i >= a.length && j < b.length) return false;
    if (j >= b.length)
      return a
        .substr(i)
        .split("")
        .every((el) => !isCapitalLetter(el));

    if (memo[i][j] !== undefined) return memo[i][j];

    if (a[i] === b[j]) {
      memo[i][j] = solve(i + 1, j + 1);
      return memo[i][j];
    }
    if (a[i].toUpperCase() === b[j]) {
      memo[i][j] = solve(i + 1, j + 1) || solve(i + 1, j, true);
      return memo[i][j];
    }
    if (a[i] !== b[j] && !isCapitalLetter(a[i])) {
      memo[i][j] = solve(i + 1, j);
      return memo[i][j];
    }

    memo[i][j] = false;

    return false;
  };

  return solve(0, 0) ? "YES" : "NO";
};

/**
 *
 * @param {string} a
 * @param {string} b
 * @returns {string}
 */
const abbreviation = (a, b) => {
  const memo = new Array(a.length + 1)
    .fill(0)
    .map((_, i) =>
      new Array(b.length + 1).fill(false).map((_, j) => i == 0 || j == 0)
    );

  for (let i = 1; i <= b.length; i++) {
    for (let j = 1; j <= a.length; j++) {
      //   console.log(a[j], b[i], j, i);
      if (a[j - 1].toUpperCase() === b[i - 1]) memo[j][i] = memo[j - 1][i - 1];
      else if (!isCapitalLetter(a[j - 1])) memo[j][i] = memo[j - 1][i];
      else memo[j][i] = false;
    }
  }

  //   console.log(memo);
  return memo[a.length - 1][b.length - 1] ? "YES" : "NO";
};

const testCases = JSON.parse(
  '[["OPZFFVQLADBQFBXLOSUMZZWQUKASCUVQZZVWfPIRTytlvpijddqegbwitkhhsbuehtnpndvcandzjzyepvlnkayfkwzegvbratvwezddjqxrxocqgcghuohlmsondvicocltqhvqfqjpctxfomjoukrheijhhndcbipiobvpbskemgykepokluwqhhejdaimvdvlegfyrrwckgojsbsxmsvhhrlnvcrxfaxinjzsjgvvrlcczqlkvgtftsvktvhtfpaklumhkovphilrappbvkarfhvwxxtrugypracozyqyvaqjityoiyemyavpbchaoagrvujocpueczsgcqdjvkjckxhmnaseshjgecusrxozuxgeieleewwskmiprlqnshvmcp","OPZFFVQLADBQFBXLOSUMZZWQUKASCUVQZZVWPIRT"],["WLWlVFFTKWXXVNXUAHAWBKCQMKEHKSJNLLISGUWMDTkURJTLXyJFEHQYTCuRFXRDHSFPIRCCQSDRRHCSDPKXGOCHFAWKPGMCZICTFFTNZBANHHELBMAWVPRekbsqbxqqwsizsjnnorxamaoudznbaqanqtucsrouxcdxfqahygyupaxfvtvigahlkpoduwmgvbvwshvazgsjkimnbjvzvwtdlomsfatfxxsfdvxcyfiycehomhhaaginwnrtoqtkhvmjikzymaqppjbtjomfjn","WLWVFFTKWXXVNXUAHAWBKCQMKEHKSJNLLISGUWMDTURJTLXJFEHQYTCRFXRDHSFPIRCCQSDRRHCSDPKXGOCHFAWKPGMCZICTFFTNZBANHHELBMAWVPR"],["PDXCyKDOkWPOTXQUEQHOEIaIAROHeAXrGISVQbnksreozjryuzlttptkufhzaqejqszwsscpsbrfjrqaixtfvazzihgrnkgrultyewhaniegnzqapbzugermphypdryqcobcglcytzcysjbuchazswrvckkmwgityneeyqeflcyhesmdhsskudnsuqtlvpplothlpilpffyuyvnjvymiwrrqappuwbinbgcb","PDXCKDOWPOTXQUEQHOEIIAROHAXGISVQ"],["RUJNEGMMMEGIRGILRHKWKSNZWMQAFKISNVVBOVNZBHRITDHZIKHXuZRRJOVNHIKLBIZTTHQCDRDDPQIWIJRAKXSAFKNZQQTUCGYBKKIFJBKYDLICJZZCDSHRCKRNXTNZAKNNFPLCLBMJJGOZLIIJYFIMYHPNHLXGZICXOCDNWKKEMGOSJUGVXIEGBWLNGXUQNBWKJIUURRBZYBKEVUSDUpAUQKVANNJWNJZZAIJCYTJPUMIYAFJKBBCEDOGWVUCTBRhHXTTZDFTPYTypxornxsclmxzsuwaqlsjwpztodbwnowpplxcvbpubodwobdlwphmcyenwdjwdzwblrejfhvoprxsiekxz","RUJNEGMMMEGIRGILRHKWKSNZWMQAFKISNVVBOVNZBHRITDHZIKHXZRRJOVNHIKLBIZTTHQCDRDDPQIWIJRAKXSAFKNZQQTUCGYBKKIFJBKYDLICJZZCDSHRCKRNXTNZAKNNFPLCLBMJJGOZLIIJYFIMYHPNHLXGZICXOCDNWKKEMGOSJUGVXIEGBWLNGXUQNBWKJIUURRBZYBKEVUSDUAUQKVANNJWNJZZAIJCYTJPUMIYAFJKBBCEDOGWVUCTBRHXTTZDFTPYT"],["CIVQEESyFYnGDSSUUUGMPXYUKRMLXRXtWAWKQRUWCXKBMTGDOWSPRFOCUOETTLIWeXTUHSSPWYQKJSIlRJGOIDARFIILFXQUBCXUQHJCtJXTJBOSJKJUAIFaBVQWBXWZIYRMYOCVYGTCJJjDMBAESZlXMDPIREZHVJGJQHAFQGGXLzIEAPcZGBOEHDXQIUDfBEYQOjTYJUJVTWEIXcBUYEyXHPDYAEHOZDPHAQAYEQNKoVBOOMTUOJHyFOLRmVKMwFVCJMTAMFVPAGYYIBZZLCPJYXLWXMHLVXXQOGSZKGZZOENOSNHJNOMXxNMRZGODIUnEZGRDFLNuZJASKXHMSJGIWGIUYWPPXQQZYDSISXFQRPLHFPHMZMGMVOLXeJWYZOZUEOHWZOFUQEGEGLPRISELSNHIGDlLqEDCCDJYKAFTLLPIYUQENFuWJJFHUAECO","CIVQEESFYGDSSUUUGMPXYUKRMLXRXWAWKQRUWCXKBMTGDOWSPRFOCUOETTLIWXTUHSSPWYQKJSIRJGOIDARFIILFXQUBCXUQHJCJXTJBOSJKJUAIFBVQWBXWZIYRMYOCVYGTCJJDMBAESZXMDPIREZHVJGJQHAFQGGXLIEAPZGBOEHDXQIUDBEYQOTYJUJVTWEIXBUYEXHPDYAEHOZDPHAQAYEQNKVBOOMTUOJHFOLRVKMFVCJMTAMFVPAGYYIBZZLCPJYXLWXMHLVXXQOGSZKGZZOENOSNHJNOMXNMRZGODIUEZGRDFLNZJASKXHMSJGIWGIUYWPPXQQZYDSISXFQRPLHFPHMZMGMVOLXJWYZOZUEOHWZOFUQEGEGLPRISELSNHIGDLEDCCDJYKAFTLLPIYUQENFWJJFHUAECOMN"],["VUWELCNJMNWLMJLZRASXaZCTBXKLLELZNWNZXNBTAPKRBBsXBJHMBDPDQDIFCXHXWNVMTFHSNAJhRSUAIAXLNICSBCIOLOAMAOAPGJVXEFBGEFCKQzMAFTVZKMGIXEKVWMbQPZTFHVLSQGBXEaFRKAMMICCGDPXWGZTGJWRCRBQIpCRBIAYRDXLMWNGEUMELKAZANQBLKTTVKQJOSZRNHUJBNDFTNFJVUNrGWKWALLBERYEgXMSXRMWHKQIFRQELUHOFGVyLESCNBWOSTOPRQYIDDTWNUCrBOOUMTLKNDRXTDPGQQERPFRJQEGEFLDUayvvmqaaypkxezuhsopxexsnfdaxc","VUWELCNJMNWLMJLZRASXZCTBXKLLELZNWNZXNBTAPKRBBXBJHMBDPDQDIFCXHXWNVMTFHSNAJRSUAIAXLNICSBCIOLOAMAOAPGJVXEFBGEFCKQMAFTVZKMGIXEKVWMQPZTFHVLSQGBXEFRKAMMICCGDPXWGZTGJWRCRBQICRBIAYRDXLMWNGEUMELKAZANQBLKTTVKQJOSZRNHUJBNDFTNFJVUNGWKWALLBERYEXMSXRMWHKQIFRQELUHOFGVLESCNBWOSTOPRQYIDDTWNUCBOOUMTLKNDRXTDPGQQERPFRJQEGEFLDU"],["ETAUMPZFGJVEUUBFDIMJPMOCRQXMMMYPUKFRJLCXOCLMUMMUHQNKIAZSKHRLPNhRRPmNIBNCHRZBYWAPUNMDFGPDKQUBZYPEIZILJEHNZGHSNSRZACYCKQSSFHEDYCMVAovcuyjahwtmgcctvjqnpgwrurwnmbifbtyqyuoafezegpecjgmkwfstjwlkromioak","ETAUMPZFGJVEUUBFDIMJPMOCRQXMMMYPUKFRJLCXOCLMUMMUHQNKIAZSKHRLPNRRPNIBNCHRZBYWAPUNMDFGPDKQUBZYPEIZILJEHNZGHSNSRZACYCKQSSFHEDYCMVA"],["KBJYYWPSOMDASRHPARGRyOZaAOEWVDTRWRKVGsgRWeVWCUVTCLYLGLZQAUHOOLJKPUCTCYJIWOKkEGRAOJAQLZABAYXHBdLptHZYVFMZCCGAQJShlHXHVCZFCBGPZDZGQHFVGLHBBvDNSUPYNJMOYHZMXRAHUZHCjNtTWSJGDUKJbRBgJRTVtHGHLKKTHBMtPMQVTKNRNOlSCBMXWJJZHFTHBNMNOBBYQTDXREdHwVBHQqKUSEDVYAEcYLGGvQKaUORVFUOFPTXGGQiLOKFRkGXBYNEQZXDFQBmPvFBUFEBNOFVQHjRJVQHsPJNXBOTKLMVRDPHXNNHwVPlKQJLWUYYAFOIUNhARELQUaBYxHRFqXGLRMFGOMPRKLZLRNRJDLJHDLMHKALTKSW","KBJYYWPSOMDASRHPARGROZAOEWVDTRWRKVGRWVWCUVTCLYLGLZQAUHOOLJKPUCTCYJIWOKEGRAOJAQLZABAYXHBLHZYVFMZCCGAQJSHXHVCZFCBGPZDZGQHFVGLHBBDNSUPYNJMOYHZMXRAHUZHCNTWSJGDUKJRBJRTVHGHLKKTHBMPMQVTKNRNOSCBMXWJJZHFTHBNMNOBBYQTDXREHVBHQKUSEDVYAEYLGGQKUORVFUOFPTXGGQLOKFRGXBYNEQZXDFQBPFBUFEBNOFVQHRJVQHPJNXBOTKLMVRDPHXNNHVPKQJLWUYYAFOIUNARELQUBYHRFXGLRMFGOMPRKLZLRNRJDLJHDLMHKALTKSWGTVBRLNKGBW"],["UZJMUCYHpfeoqrqeodznwkxfqvzktyomkrVyzgtorqefcmffauqhufkpptaupcpxguscmsbvolhorxnjrheqhxlgukjmgncwyastmtgnwhrvvfgbhybeicaudklkyrwvghpxbtpyqioouttqqrdhbinvbywkjwjkdiynvultxxxmwxztglbqitxmcgiusfewmsvxchkryzxipbmgrnqhfmlghomfbsKjglimxuobomfwutwfcmklzcphbbfohnaxgbaqbgocghaaizyhlctupndmlhwwlxxvighhjjrctcjBvxtagxbhrbrWwsyiiyebdgyfrlztoycxpjcvmzdvfeYqaxitkfkkxwybydcwsbdiovrqwkwzbgammwslwmdesygopzndedsbdixvi","UZJMUCYH"],["AITDVQYyBXUHBBTXvJOCCHGHXPWOYEHSKNAQHSDIWJHKDYMODFAYKNYAJUFCQZPAVTZYPbJFRDYSuDNYMFRKADBTQOBXSNeWDQYHBSLMTDdZiUJECURIEBZPNRByMAQNNGXGHAWTOKAKOAVgPDEAOEPSZHGNISBHVLIDRMNAFBHGPBYRhdJEPKLOOlYnJYXEOSWCOGEEWJDPKQXEDGUSZSAYzWLWQEVFHBTLAFTFZTXkQJWEHVaRFNTAEQDJVYKSBAFNUfGJMByRKINGTSLBIEDCMFOHGmICOCKGPZXHglLBUWUUTTSBNVQceMIEwKAOWAANJYqYKoYIOXtYHDKDNVVZOKPJvTLKoKBJMAEMSVUFKYQTSGXNDQLEAdUAzIXGOSWCLXFVTAWSQDWDCLdARUIQRFRSMBQACKAGLMGYFCCJMTLSOEPJXIIIZSPBXvHeYFVMjcarjwckioyvkzzjfytwcqzkrqukjxhvmywrcbulvznma","AITDVQYBXUHBBTXJOCCHGHXPWOYEHSKNAQHSDIWJHKDYMODFAYKNYAJUFCQZPAVTZYPJFRDYSDNYMFRKADBTQOBXSNWDQYHBSLMTDZUJECURIEBZPNRBMAQNNGXGHAWTOKAKOAVPDEAOEPSZHGNISBHVLIDRMNAFBHGPBYRJEPKLOOYJYXEOSWCOGEEWJDPKQXEDGUSZSAYWLWQEVFHBTLAFTFZTXQJWEHVRFNTAEQDJVYKSBAFNUGJMBRKINGTSLBIEDCMFOHGICOCKGPZXHLBUWUUTTSBNVQMIEKAOWAANJYYKYIOXYHDKDNVVZOKPJTLKKBJMAEMSVUFKYQTSGXNDQLEAUAIXGOSWCLXFVTAWSQDWDCLARUIQRFRSMBQACKAGLMGYFCCJMTLSOEPJXIIIZSPBXHYFVM"]]'
);

testCases.forEach((el) => console.log(abbreviationRec(...el)));
